[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -Xms1g -Xmx1g -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar app.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
healthcheckInterval = 30