[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "java -Xms512m -Xmx512m -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar app.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10